disabled_rules: # 执行时排除掉的规则
- shorthand_operator
- multiple_closures_with_trailing_closure
- identifier_name
- return_arrow_whitespace
- file_header
- implicit_getter
opt_in_rules: # 一些规则仅仅是可选的
- closure_end_indentation
- closure_spacing
- file_header
- multiline_parameters
- vertical_parameter_alignment_on_call
# 可以通过执行如下指令来查找所有可用的规则:
# swiftlint rules
included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
- TextbookUnlimited
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
- Pods
- TextbookUnlimited/Libs
- TextbookUnlimited/Unused

# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式
severity: warning # 显式
control_statement: error
colon: error
comma: error
function_parameter_count:
    warning: 20
    error: 25
line_length:
    warning: 250
    error: 450
large_tuple:
    warning: 4
type_body_length:
    warning: 450
    error: 650
function_body_length: 80
file_length:
    warning: 600
    error: 1200
mandatory_comma: true
cyclomatic_complexity:
    warning: 20
    error: 25
reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)

