platform :ios, ‘8.0’
target "TextbookUnlimited" do
    use_frameworks!
#    # 弹幕
#    pod 'BarrageRenderer', '~> 2.1.0'
    # 网络
    pod 'ReachabilitySwift', '~> 4.1.0'
    pod 'Alamofire', '~> 4.6.0'
    # json
    pod 'SwiftyJSON', '~> 4.1.0'
    # 设备
    pod 'DeviceKit', '~> 1.8.1'
    # 代码风格
    pod 'SwiftLint', '~> 0.27.0'
    # 刷新
    pod 'MJRefresh', '~> 3.1.15.7'
    # 约束
    pod 'SnapKit', '~> 4.0.0'
    # 键盘
    pod 'IQKeyboardManager', '~> 6.1.1'
end
